#!/bin/bash
# 🎉 HARmony App - Final Complete Setup Script
# Run these commands in separate terminals
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         HARmony App - Complete Setup & Run Guide              ║"
echo "║                 Status: ✅ PRODUCTION READY                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 COPY & PASTE THESE COMMANDS IN SEPARATE TERMINALS:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 1 - START FLASK BACKEND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd ~/backend"
echo "python app.py"
echo ""
echo "Expected: * Running on http://127.0.0.1:5000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 2 - START POSTGRESQL (macOS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "brew services start postgresql"
echo ""
echo "OR (Linux):"
echo "sudo systemctl start postgresql"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 3 - CONFIGURE THEN RUN FLUTTER APP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 1: Edit backend URL"
echo "nano ~/Documents/Final_Project/HARmony_Frontend/harmony_app/lib/core/app_providers.dart"
echo ""
echo "  Find line ~32 with: String baseUrl = ..."
echo "  For Emulator: String baseUrl = 'http://10.0.2.2:5000';"
echo "  For Device:   String baseUrl = 'http://192.168.1.5:5000'; // Your IP"
echo ""
echo "STEP 2: Get your machine IP (if using physical device)"
echo "ifconfig | grep 'inet ' | grep -v 127.0.0.1"
echo ""
echo "STEP 3: Run the app"
echo "cd ~/Documents/Final_Project/HARmony_Frontend/harmony_app"
echo ""
echo "# FOR EMULATOR:"
echo "flutter run"
echo ""
echo "# FOR PHYSICAL DEVICE:"
echo "flutter devices                    # Show connected devices"
echo "flutter run -d <device_id>        # Replace with device ID"
echo ""
echo "# FOR RELEASE BUILD:"
echo "flutter run --release"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ EXPECTED OUTPUT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ Built build/app/outputs/flutter-debug.apk"
echo "✓ Installed build/app/outputs/flutter-debug.apk"
echo "🔗 API Service configured to: http://10.0.2.2:5000"
echo "✓ Connected to Flask backend"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 QUICK TEST IN APP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Home screen loads ✓"
echo "2. Tap 'Real-time Recognition'"
echo "3. Tap 'Start Monitoring'"
echo "4. Walk around (move device)"
echo "5. See real-time predictions ✓"
echo "6. Tap 'Stop'"
echo "7. Check 'History' → Session appears ✓"
echo "8. Toggle 'Dark Mode' → Theme switches ✓"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🐛 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Backend won't start:"
echo "  lsof -i :5000              # Check if port 5000 in use"
echo "  kill -9 <PID>             # Kill if needed"
echo ""
echo "App won't build:"
echo "  flutter clean"
echo "  flutter pub get"
echo "  flutter run"
echo ""
echo "Device won't connect:"
echo "  adb kill-server"
echo "  adb start-server"
echo "  flutter devices"
echo ""
echo "Check Flask is running:"
echo "  curl http://localhost:5000/api/health"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOCUMENTATION FILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "START_HERE.md                    - Quick overview"
echo "RUN_COMMANDS_ANDROID.txt         - Step-by-step visual guide"
echo "SETUP_AND_RUN_GUIDE.md           - Complete detailed guide"
echo "QUICK_COMMANDS.md                - Command reference"
echo "FINAL_IMPLEMENTATION_SUMMARY.md  - What was implemented"
echo ""
echo "All files in: /home/ilavarasi/Documents/Final_Project/HARmony_Frontend/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ STATUS: PRODUCTION READY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Backend:        Flask with PostgreSQL"
echo "✅ Frontend:       Flutter 3.8+"
echo "✅ UI/UX:          Material 3 (Light + Dark)"
echo "✅ Features:       All Implemented"
echo "✅ Documentation:  Comprehensive"
echo "✅ Errors:         None"
echo ""
echo "Ready for development, testing, and production! 🚀"
echo ""
